name: wecycle
description: An Android and iOS app that scans a recylable item and rewards users for recycling it. 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  camera: ^0.5.6
  video_player: ^0.10.2
  path_provider: ^1.4.2
  giffy_dialog: ^1.6.0
  image_picker: ^0.6.2+3

dev_dependencies:
  stack: ^0.0.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  assets:
    - assets/images/WeCycle.png
    - assets/images/Blue_Circle.png
    - assets/images/2x/Blue_Circle.png
    - assets/images/3x/Blue_Circle.png
    - assets/images/Teal_Circle.png
    - assets/images/2x/Teal_Circle.png
    - assets/images/3x/Teal_Circle.png
    - assets/images/Ellipse_4.png
    - assets/images/2x/Ellipse_4.png
    - assets/images/3x/Ellipse_4.png
    - assets/images/leftkeyboardarrow.png
    - assets/images/2x/leftkeyboardarrow.png
    - assets/images/3x/leftkeyboardarrow.png
    - assets/images/rightkeyboardarrow.png
    - assets/images/2x/rightkeyboardarrow.png
    - assets/images/3x/rightkeyboardarrow.png
    - assets/images/Rectangle_16.png
    - assets/images/2x/Rectangle_16.png
    - assets/images/3x/Rectangle_16.png
    - assets/animations/checkmark-animation.gif
    - assets/images/coin.png
    - assets/images/2x/coin.png
    - assets/images/3x/coin.png
    - assets/images/AddButton.png
    - assets/images/2x/AddButton.png
    - assets/images/3x/AddButton.png
    - assets/images/ic_star.png
    - assets/images/2x/ic_star.png
    - assets/images/3x/ic_star.png
    - assets/images/ic_people.png
    - assets/images/2x/ic_people.png
    - assets/images/3x/ic_people.png
    - assets/images/Earth.png
    - assets/images/2x/Earth.png
    - assets/images/3x/Earth.png


fonts:
  - family:  Segoe
    fonts:
      - asset: assets/fonts/Segoe_UI.ttf
      - asset: assets/fonts/Segoe_UI_Bold.ttf
      - asset: assets/fonts/Segoe_UI_Semi_Bold.ttf

  - family:  ButtonIcons
    fonts:
      - asset: assets/icons/ButtonIcons.ttf




